name: contact_cardio
version: 0.0.0
author: Ryan Hiroaki Tsukamoto<backward6@gmail.com>
description: A package for reading and writing various contact information formats such as vCard and MeCard.
homepage: https://github.com/71241NW123CK/contact-cardio-dart

environment:
  sdk: '>=2.0.0 < 3.0.0'

dev_dependencies:
  build_runner: '>=1.7.0 <2.0.0'
  test: '>=1.9.0 <2.0.0'
